### ISSUE TITLE
People can update with an older version of Vitashell installed on their system

### ISSUE THREAD

**Issue by mathieulh** [TheOfficialFloW/update365#1]
Because Vitashell is not installed by the enso installer and the auto update feature is broken as github enforced tls 2.0 (or the vita is not connected online), some users update to enso 3.65 while having a version of vitashell incompatible with 3.65, leaving them in dissaray. The only workaround to this issue is to import a modified CMA backup with the latest version of Vitashell in it. Vitashell should be installed by the enso installer or installing the latest version of Vitashell should be clearly mentioned in the readme.

**Comment by RY0M43CH1Z3N** [comment]
You can use molecularshell to install the new update for vitashell

**Comment by dude22072** [comment]
Can confirm having run into this issue my self that molecularshell cannot be used to fix the issue,

In the end I fixed it by simply replaing the eboot.bin with the newer one.

**Comment by tloberif** [comment]
I fixed simply(too) replaing the eboot.bin with the newer one...thanks

**Comment by coolcono** [comment]
Where did you get the eboot.bin? I think have the same problem.

**Comment by coolcono** [comment]
I am relatively new. Could I ask where is the new Eboot?

**Comment by mathieulh** [comment]
Since installing the latest version of Vitashell is clearly stated within the readme, I consider that people should read before attempting this update and therefore this issue to be closed. 

The Flow can feel free to add vitashell installation to the installer and/or reopen this issue for any reason whatsoever.

**Comment by Raytwo** [comment]
I made the update while convinced that I had the latest VitaShell but didn't. 
Fixing this is easy:
Open MolecularShell, remove the VitaShell app from /app and the /vitashell folder in ux0:, then try reinstalling the latest VPK and it'll work.
