### ISSUE TITLE
PSPUPDAT.PUP disappears

### ISSUE THREAD

**Issue by edale2** [TheOfficialFloW/update365#11]
While still on 3.6 firmware (I'm now on 3.65, so won't risk testing further)

When:

PSPUPDAT.PUP is in ux0:app/UPDATE365/
VitaShell.vpk (1.83) is in ux0:VPK/
updater.vpk is in ux0:VPK/

From MolecularShell install VitaShell.vpk
Exit MolecularShell and enter VitaShell.
in VitaShell install updater.vpk.

I'm not sure if it's VitaShell install, or the updater's install, but on of the two deletes PSPUPDAT.PUP, and populates the ux0:app/UPDATE365/ with:

eboot.bin
kernel.skprx
kernel2.skprx
user.suprx
/livearea/contents/icon.png
/livearea/contents/param.sfo
sce_sys/livearea/contents/bg0.png
sce_sys/livearea/contents/startup.png
sce_sys/livearea/contents/template.xml
sce_sys/package/head.bin
sce_sys/package/work.bin

Requiring you to re-upload PSPUPDAT.PUP to the ux0:app/UPDATE365/ folder.

This happened twice on a PSTV while trying to get the updater to work, so not a one-time glitch.

**Comment by TheOfficialFloW** [comment]
The instructions said to install updater.vpk first then upload PSP2UPDAT.PUP.

**Comment by edale2** [comment]
Ah, that didn't make it into the video I was following to update my PSTV.Awesome work on this (and well timed given I just got my PSTV 3 days ago, lol). NA release of Ys VIII Lacrimosa of DANA (I got tired of waiting on the PC port) here I come!
