### ISSUE TITLE
Cannot Mount Memory Card to um0

### ISSUE THREAD

**Issue by KUR0GAMI** [TheOfficialFloW/update365#14]
Hi,
I think there's a closed issue about this and no result at all.
Maybe this isn't the right place to ask about why we can't mount memory card as um0 while using SD2VITA as ux0 (I should ask this at SD2VITA forum). But this issue happened when using 3.65, and we cannot mount um0 because this slot, for USB flash. Maybe someone had figured it out how to change this config so will not be overlapped by this setting.
Thanks. 

Never mind. I think I'm so stupid lol.

**Comment by iamgroog** [comment]
Try ti use  [PSVita-StorageMgr](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/releases) plugin with follow config:
GCD=ux0
MCD=uma0
UMA=grw0
INT=imc0
