### ISSUE TITLE
an FTP issue in vitashell v1.94 

### ISSUE THREAD

**Issue by iDevIceXsi** [TheOfficialFloW/update365#20]
Recently i discovered that while using vitashell and creating a FTP connection, if you leave it on in the background and install a package for instance after the installation is done vitashell forgets the FTP as if it wasnt turned on. it shouldnt happen since when you have FTP on vitashell wont let you exit till you close it. tested twice on 3.60 henakku enso with sd2vita.

**Comment by TheOfficialFloW** [comment]
Is this an issue with 3.65 enso? No. So why do you submit the issue here dude?

**Comment by iDevIceXsi** [comment]
new here sorry

**Comment by iDevIceXsi** [comment]
really am 
tried to get to you and freakler told me to hit u up here github am new so.. sorry

**Comment by TheOfficialFloW** [comment]
Nothing to do with being new or not, you just simply can't differentiate the letters between "VitaShell" and "update365".
