### ISSUE TITLE
Enso Brick - PLEASE fix this terrible program

### ISSUE THREAD

**Issue by AngryBrickedVITA** [TheOfficialFloW/update365#23]
So i have installed enso on my 3.65 vita, the OFW i left it on when i purchased it on Amazon, i had so much newbie trouble trying to get nonpdrm to work after installing sd2vita, i tried to reinstall 3.65 ofw thinking i made a mistake or an error during the process of installing all these plugins addons apps etc. I finally gave up and updated to 3.68 thinking f*ck enso it isnt worth the trouble, so the next day i wake up get all my stuff installed again, (but i didnt reinstall adrenaline) ignoring pkgj, since i used Nopaystation from my pc and USB'd Call of duty over to my vita, i refresh the live area after the usb transfer completes, no call of duty (not sure wtf is going on still having issues apparently) so i notice i have Adrenaline back and the Enso Bubble, both back! how? idk i really dont so i go to Enso, i use the enso-built in uninstaller, it succeededs and forces a restart. Now i have reached the BRICKED phase, where my system will power on but show a black screen. I have tried holding the power button for 20+ seconds, it only cycles the power from on to off and right back to on and still sits on a black screen. A fix would be nice, i bought this ps vita, an sd card and an sd2vita last week, hoping to play some games now ive got 150$ down the sh*tter and a dead psv. Please fix Enso so this doesnt occur to other users!
this appears to be the wrong Enso program, i DID NOT use this program i used the 1.0 release version of 3.65 enso
this version of enso to be specific is the cuplrit that i used that f*cked my vita over 
https://github.com/TheOfficialFloW/enso/releases
if anyone has a fix for a bricked vita thru enso's unreliable flaws id be glad to try it. also i didnt know anywhere else to contact theflow, considering i dont have twitter

also, what more can/shall i do with my bricked vita? bring it to gamestop and tell them i dropped it and the screen no longer works and have them give me like 10$ for it? (im not the real thief here... we all know gamestop policy is a joke on returns)

**Comment by TheOfficialFloW** [comment]
https://www.reddit.com/r/vitahacks/comments/8v701k/psa_do_not_updatereinstall_360_and_then_also/

**Comment by AngryBrickedVITA** [comment]
can i send you my vita for components? ive no use for it now
