### ISSUE TITLE
Custom string in System Information not showing

### ISSUE THREAD

**Issue by GrayJack** [TheOfficialFloW/update365#7]
It's a minor thing
Since the update, after I set up my tai/config.txt, the custom string isn't showing anymore.
I did change the "ur0:tai/henkaku.suprx" to "vs0:tai/henkaku.suprx" on main, NPXS10015 and NPXS10016

**Comment by TheOfficialFloW** [comment]
you don't need to put anything into config.txt, henkaku.suprx is now hardcoded to load.

**Comment by GrayJack** [comment]
Ok, I removed them, rebooted, but still the custom string still don't show up in System Information

**Comment by TheOfficialFloW** [comment]
Does HENkaku Settings appear though? Deactivate all plugins and try again (rebuild database)

**Comment by GrayJack** [comment]
Henkaku Settings appears. I did rebuild database, but nothing changed, it still only shows 3.65, but not the custom string

**Comment by TheOfficialFloW** [comment]
What model are you using?

**Comment by GrayJack** [comment]
Ps Vita 1k 3G, I don't use the psvsd

**Comment by TheOfficialFloW** [comment]
There was a bug in the henkaku module. Enable psn spoofing will display the custom string.

**Comment by GrayJack** [comment]
There is any way to update henkaku with the string fix?

**Comment by TheOfficialFloW** [comment]
Enable psn spoofing

**Comment by GrayJack** [comment]
Yeah, I know, I was asking if I can compile henkaku with the commit that fix it and install it in vs0:/tai
