### ISSUE TITLE
3.65 henkaku enso updater says file is corrupt.

### ISSUE THREAD

**Issue by nightwishfan1** [TheOfficialFloW/update365#8]
I contacted you over at reddit about this as well, but the henkaku enso updater is constantly telling me the update file is corrupt when I go to install it.  I have it placed at ux0:app under the UPDATE365 folder you specified.  I have downloaded this file at least 3 times from your own release page here on github, and nowhere else.  Neither time did it seem to want to work.  Just the file is corrupt from the updater.  I've only transferred the file over via vitashell 1.82 to it's proper location via usb drive after download from my pc.  Just to be clear I have restarted and re-installed henkaku after use of vitashell 1.82 each time.  So it's definitely not a error on my end.

So I got no idea what's going on.  Only thing as I noted on reddit that is different is the file sizes.  Your release page here says the file should be 128MB where as vitashell and molecular shell (I checked both) report it at 127.56 I believe the exact figure was.  Just wanted to let you know about this as I'm sure I'm not the only one with this peculiar issue.   Thanks.

**Comment by TheOfficialFloW** [comment]
download it from an other source then

**Comment by nightwishfan1** [comment]
So.....That's it?  You just want to ignore it when your sources are going to the be the most trusted?  Wow man lol.  Thanks anyway I guess.

**Comment by TheOfficialFloW** [comment]
What do you expect me to do? It‘s working for everyone else so what can I do? Upload it twice? Fix your internet? The updater should verify the pup file anyways so whether you trust your source or not does not matter, only the correct file will be accepted.

**Comment by TheOfficialFloW** [comment]
oh and I have got the feeling that you didn't install updater.vpk since on reddit you said that you have created the folder ux0:app/UPDATE365 which is not neccessary.
